### PR TITLE
Score method

### PR DESCRIPTION
**Pull request by JodesL**
Hi @dswah, I have added a GAM.score method to the base GAM class following from issue #102.
I have also added a simple test for the score method to quickly check that it the score method without crashing and checks that the score which is R^2 is <=1.

Currently it only calculates the R^2 which is the default score in scikit-learn for regression models. I can also add the accuracy score specifically to the LogisticGam class. 

I am quite new to github and this whole open source concept, so I would appreciate any feedback!
Let me know if the code makes sense or if I am completely off.
Thanks!

### CODE REVIEW

**Comment by dswah** [comment]
@JodesL This is amazing!! Thank you!

A couple of initial comments:
- Computing R^2 based on reduction in squared error makes sense for models with normal distributions, but not necessarily for others.
- So, we could move this method to the `LinearGAM` class
- **OR** we could use a generic scoring method that returns the `explained_deviance` version of R2 from https://github.com/dswah/pyGAM/blob/01d70f6f9ec32cd8abf31a41372e2e6ee3d09010/pygam/pygam.py#L1120 This is equivalent to the method you wrote in the case of the normal distribution.

I will take a look closer this weekend :)
Thanks again for contributing!

**Comment by dswah** [comment]
Very cool that you included a test :+1:

**Comment by JodesL** [comment]
@dswah Thanks for replying!
I think the option that returns explained deviance for all generic gams would be best. It would then depend on the deviance defined for each distribution which makes sense.

As for `LogisticGam`, I am thinking I can just override gam.score() with accuracy instead of R2.

Let me know your thoughts 😀

**Comment by dswah** [comment]
@JodesL I'm sorry for not replying! I have just started a new job and have been quite busy.
Your changes look great. I will merge them this weekend!

**Comment by dswah** [comment]
@JodesL 
I would like to change the pyGAM license to allow proprietary use of the library, which means downstream users would NOT need to release the source-code of their application when they use pyGAM.

The current GPLv3 license is quite strict, and the hope is that a more passive license will encourage (proprietary) contributors to keep improving this library.

Please let me know if you are ok with this change.
Thanks,
Danny

PS:
I am considering the following licenses:
- [Lesser GPLv3](https://choosealicense.com/licenses/gpl-3.0/), (tldr: any modifications must be made open-source, but downstream applications do not need to be open-sourced, and can use a different license)
- [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) (tldr: any use and modifications are allowed, with any license, with or without release source-code. all modifications must be explicitly stated.)
- [MIT](https://choosealicense.com/licenses/mit/) (tldr: you can do anything you want with the software, and the software comes with no warranties)


Current [GPLv3 license](https://choosealicense.com/licenses/gpl-3.0/) for reference. (tldr: any modifications and downstream applications must be made open-source and released with the same license)

**Comment by JodesL** [comment]
@dswah The changes to the license seems great, would encourage more usage of the package for sure!
And no worries I have also been busy recently.

**Pull request merged**
