### PR TITLE
Compatibility with  numpy 1.24

### LINKED ISSUE #326: Code is incompatible with numpy 1.24.1
The code uses `np.int` which is no longer supported in numpy version 1.24.1. The PR #325 suggests to replace it with `np.int_`.

### PR DESCRIPTION
**Pull request by gedeck**
With the latest release of numpy 1.24.0, numpy deprecated and removed `np.int`. This PR replaces `np.int` with `np.int_`. The change was tested using numpy 1.23.5 and numpy 1.24.1 with Python 3.10.9.

If you merge the PR, please release a new version of pyGAM on pypi.

Closes #326

### CODE REVIEW

**Comment by gedeck** [comment]
> Having the same problem. If I understand correctly, just using `int` instead of `np.int` should solve the problem. Is there any advantage for `np.int_`?

According to the numpy documentation, `int` is interpreted as `np.int_`. I make this change.

**Comment by Alexander-Serov** [comment]
Thanks! This is how I'm reading numpy's message. 😀

**Review by Alexander-Serov — APPROVED** [review]
Thanks for finding time!
Let's hope someone merges it. 🤞🏻 Need  someone with write access to the repo, right?

**Comment by Alexander-Serov** [comment]
@dswah Could you approve?

**Comment by gedeck** [comment]
Looks like the necessary changes were made to the main code and a new version released recently. I will close the PR.

Thank you for getting the new version out.

**Pull request closed without merging**
