### PR TITLE
feat: add python 3.11 support, fix installation and ci

### LINKED ISSUE #319: Can't use flit to install pygam - pyproject.toml does not exist
I have been trying to install pygam from source using flit, as indicated in the docs, but I am unable to do so.

I have been running the following (from the project's root directory):

`pip install flit`
`flit install -s`

And after running `flit install` I get the following error:

`Config file pyproject.toml does not exist`

So it seems like the config toml file for installation is missing.

**Environment details**
Python 3.6.13
Flit 3.7.1

### PR DESCRIPTION
**Pull request by jmahlik**
BREAKING CHANGE: drop python 2 support, minimul required python is 3.8+

* Add official support and testing for python 3.8-3.11.
* Updated the ci to run on python 3.8-3.11 and removed conda from ci (didn't seem needed).
* All tests pass locally on python 3.11 without scikit-sparse installed.
* The ci tests may have a problem on python 3.11 since scikit-sparse doesn't appear to support it. Can be adjusted as needed. Maybe don't install sparse on the python 3.11 tests.
* Drop support for python 2-3.7. 3.7 is end of life in 4 months.
* Fix the build system and move to `pyproject.toml`
* Restricted numpy version until it is fixed by https://github.com/dswah/pyGAM/pull/325.

Closes #319 #312

@dswah would you mind having a look at this PR? pyGAM is having some difficulties with newer versions of python and numpy.

It looks like there hasn't been a release in quite some time. Wondering if you still have interest in maintaining this project? I am willing to help maintain the project if possible. Let me know thoughts :).

### CODE REVIEW

**Comment by miguelfmc** [comment]
Are there any plans to accept this PR?

Echoing what @jmahlik said - it would be great to have pyGAM work smoothly with more recent Python versions.

I'm also happy to help with the project although I'm quite the newbie when it comes to open source.

**Comment by Zethson** [comment]
@dswah are you willing to give someone else maintainer rights so that the community can take this over?

**Comment by dswah** [comment]
Yes i am happy to give the community maintainer rights!
@Zethson

**Comment by Zethson** [comment]
Maintainer question aside, I don't get why you closed instead of merging this PR

**Comment by dswah** [comment]
I didnt merge because the main functionality from this PR has been in production since March 2023 after the merge of PR https://github.com/dswah/pyGAM/pull/332 

Admittedly, I should have had a conversation with the original contributor a month before that, because there were a few issues with this PR (that were addressed in https://github.com/dswah/pyGAM/pull/332). Specifically:
- i had been wanting to migrate to poetry for a while because the improved dependency solving removes a big headache
- this PR depends on Travis CI, which is no longer free

I'm sorry @jmahlik because I never commented on your PR when the time was appropriate, I didn't thank you for your contribution, and I closed this PR a year later with no comment to you personally. Your initiative was 100% correct. I acted wrongly and am sorry.

**Comment by jmahlik** [comment]
No worries @dswah. I saw the other PR so should have closed this one, just didn't get around to clicking the button in time.

**Comment by CodeCrux21** [comment]
> Yes i am happy to give the community maintainer rights! @Zethson

Who has maintainer rights? I currently have two open PRs I'd like merged.

**Pull request closed without merging**
