### PR TITLE
Fix not-None element existance judgement bug

### PR DESCRIPTION
**Pull request by BeefOnionDumplings**
Fixed a bug that the function want to judge whether element == None for each element in the ndarray but actually judge whether None == array itself.

### CODE REVIEW

**Comment by BeefOnionDumplings** [comment]
The Error occured When I was running the example code in the documentation, saying "bool type doesn't have method 'any'". I watched it in the debugger and I found the value of (np.atleast_1d(self.constraints) != None) is False rather than ndarray[False].

**Comment by dswah** [comment]
@BeefOnionDumplings this is cool.
can you point to the code sample that caused the bug?

i'd like to include a regression test to prove that this fixes PR the issue.

**Comment by BeefOnionDumplings** [comment]
Just the example code in the quick start part of the documentation. In fact it happens when I fit any model.

**Comment by dswah** [comment]
@BeefOnionDumplings please tell me more about the bug.
i just ran the whole quickstart guide but could not replicate the error!

I am using the following system:
python 3.6
pygam 0.7.1
numpy 1.15.1
scipy 1.1.0

can you tell me more about the bug? (does it happen during the call to `fit()` ?)
what python are you using?
which pygam, numpy, and scipy?

thanks,
dani

**Comment by BeefOnionDumplings** [comment]
@dswah
It happens during the call to fit(). 
My execution environment  is python 3.5.2, numpy 1.12.1, pygam 0.7.1.
Maybe np.equal() has a better compatibility than syntactic sugar under this situation.

**Comment by dswah** [comment]
@BeefOnionDumplings thanks for the details.
i was able to reproduce the exception using numpy 1.12.1

i think it's a good idea to use this numpy value check.

**Pull request merged**
