### PR TITLE
Added Sphinx-based documentation, updated requirements.txt

### PR DESCRIPTION
**Pull request by badge**
Hi, I discovered your project last week and have already used it to great effect, and thought you might like some docs. :smile:

Commit message is below; I've hosted a copy of the [HTML docs here](http://lightrefrain.net/pygam-docs/), if you think this is worthwhile it's probably best to use readthedocs (hence my choice of theme). A few more details on the changes:

- I recreated the text and code from the README as a jupyter notebook; only the image pygam_basis.png needed including as all the others were generated in the code
  - It's easy to add a link to the notebook's source on github from the notebook itself, so people can download and run it themselves
  - This uses [nbsphinx](http://nbsphinx.readthedocs.io/), which is awesome
- The API docs are largely generated with autodoc, which uses `.. autoX::` directives; in the cases of `links` and `callbacks` I documented each class individually; for `distributions` and `penalties` you can see these are done at the module level with `automodule::`.
- Numpy-style docstrings are a great choice--they mean you can use [napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) to generate documentation from them; the [scikit-learn docs](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) are a great example of what can be created automatically [from the docstrings](https://github.com/scikit-learn/scikit-learn/blob/f0ab589f/sklearn/decomposition/pca.py#L107).

There's a lot more to be done, in particular incorporating points from [Pablo's post](https://codeburst.io/pygam-getting-started-with-generalized-additive-models-in-python-457df5b4705f) in more involved examples for classification and regression, deciding a better structure for the documentation overall, and of course working on the docstrings in the code. I didn't want to spend too much time on it before checking that you thought it worthwhile!

Commit message follows

-------------------------

Sphinx-based documentation has been added to the project;
this comes from two main sources:
- Main modules added using autodoc and napoleon
  - These are split into two sections, GAM classes and other
    helper classes and functions
  - Each GAM has its own page, while the helper classes and
    functions are grouped by module
  - Minor changes to docstrings in pygam.py to fix formatting
    issues in the output docs; there are a lot more of these
    to tackle but in general everything is pretty readable
- The text and code from the README as a jupyter notebook,
  imported using nbsphinx

Updated requirements.txt with a Documentation section,
detailing the different modules necessary to build the
documentation.

### CODE REVIEW

**Comment by dswah** [comment]
@badge this is amazing!!
ive been wanting to make a docs page for ever!

the docs look quite good so far. 
do you think it's in a presentable state?
or should we iterate some more before merging?

thanks so much for your work on this.

**Comment by badge** [comment]
You're welcome, thanks for a great Python package! Happy to do a bit more work over the next few weeks to make things a little more complete. I'll leave this request open and commit onto my docs branch.

**Comment by dswah** [comment]
@badge sounds cool.

do you have an idea for a good way to collaborate on this?
perhaps i could commit to your branch as well?

**Comment by badge** [comment]
Belatedly(!), I've invited you to join my fork as a contributor. (I haven't made any subsequent changes locally yet.)

**Comment by dswah** [comment]
i accepted! i havent made any changes either (yet!)

**Comment by dswah** [comment]
@badge ive been making commits on this branch.
make sure to do a `git pull` or similar (?) before continuing with your work!

**Comment by badge** [comment]
Ah, awesome! I’m hoping to get a bit of time to do some more work on this next week. :)

**Pull request merged**
