### PR TITLE
change license to apache2

### PR DESCRIPTION
**Pull request by dswah**

### CODE REVIEW

**Comment by cbrummitt** [comment]
Looks good to me! 👍

**Comment by dswah** [comment]
@cbrummitt can you try to review again?

**Comment by dswah** [comment]
or perhaps you can try to manually review the file?
[https://github.com/dswah/pyGAM/pull/250/files](https://github.com/dswah/pyGAM/pull/250/files)

**Comment by dswah** [comment]
thanks @cbrummitt !

**Pull request merged**
