### PR TITLE
fix deprecation warnings for np.int

### PR DESCRIPTION
**Pull request by csinva**

### CODE REVIEW

**Comment by davidusb-geek** [comment]
> @davidusb-geek
> 
> Please include this PR and make a new release on PyPI. My logs are currently spammed with the deprecation warning from numpy...

I naively thought that by approving this PR will be enough for the CI to caugth up an integrate the PR. However, a review of one of the repo owners is needed. So is up to the contributors to do this

**Review by davidusb-geek — APPROVED** [review]

**Review by marhoy — APPROVED** [review]
Looks good to me.

**Comment by marhoy** [comment]
> > @davidusb-geek
> > Please include this PR and make a new release on PyPI. My logs are currently spammed with the deprecation warning from numpy...
> 
> I naively thought that by approving this PR will be enough for the CI to caugth up an integrate the PR. However, a review of one of the repo owners is needed. So is up to the contributors to do this

@dswah : Please approve, merge and release a new version on PyPI (it's been more than 4 years since the last release)...
My logs are getting spammed by this DeprecationWarning....

**Review by spisakt — APPROVED** [review]
The fix looks good to me, unless precision has to be explicitly specified.
An update on PyPi would be nice, this now throws an error with the latest numpy.

**Comment by justinchanjinle-forty2science** [comment]
Hi @dswah , any plans to merge and release this on pypi? Thanks for your contribution. Cheers.

**Comment by jdebacker** [comment]
Including this simple fix in a new `pygam` release would be great as it's otherwise incompatible with recent versions of Numpy.  Thanks!

**Comment by lauramware** [comment]
I'm also unable to use this package because it's incompatible with recent versions of numpy. @dswah are there plans to release a new version?

**Comment by lauramware** [comment]
Never mind, I see this was fixed with the latest release so looks like this PR can be closed

**Comment by dswah** [comment]
pygam versions >= 0.9.0 fix this!
please run `pip freeze | grep pygam` if in doubt about which version you have!

**Pull request closed without merging**
